### ISSUE TITLE
Issues when running in Starfinder

### ISSUE THREAD

**Issue by danimrath** [mclemente/healthEstimate#132]
Thanks for updating the system reference. After doing some testing I've found a few other things that need attention.

1) Starfinder uses a couple more types so in the switch statement in sfrpg.js  you should probably add cases for npc2 and drone. Not entirely sure where I would put drones for the fraction or descriptions but I settled on matching with the starship personally for now.

2) Also in sfrpg.js the system does not like the default t(" references for thresholdNames and vehicleNames and will crash unless I change it to a string.

3) in utils.js the if statement doesn't differentiate between vehicles and starships or use the vehicle thresholds if the option is checked.
Something like this on line 44?
	if ([vehicleType, starshipType, droneType].includes(type)) {
		descriptions = game.settings.get("healthEstimate", type === vehicleType && game.settings.get("healthEstimate", "starfinder.useThreshold") ? "starfinder.thresholdNames" : "starfinder.vehicleNames").split(/[,;]\s*/);

**Comment by mclemente** [comment]
>1

I've added them. Drone uses the same math as PC/NPC, but uses the Vehicles' descriptions.

>2

I've missed an import there, it's a shortcut for `game.i18n.localize`

>3

Threshold Names setting has been deprecated for some time now. It is only left there in case someone that used them needed to get the setting's value back.
The Use Threshold setting now only affects the Vehicle's fraction, you can see in the the [fraction function](https://github.com/mclemente/healthEstimate/blob/feff240273d2525dac32aea3709d6dfe0ad237fa/module/systems/sfrpg.js). Its description could use a update to better describe it, but I'm not sure how. Also, I'm not sure if it should affect Starships and Drones since I don't play the system.

**Comment by danimrath** [comment]
1) Awesome that seems appropriate.
2) Fantastic, not sure why I didn't think of looking for that
3) Aha, that makes sense. Drones and Starships are not affected by threshold. Using the same list for vehicles does make it a bit clunky though. Especially since you have to make sure you don't move broken from it's relative position in the description list and it feels weird to me (though not necessarily incorrect) that it reports as Pristine until half hp. Not sure the best path forward on that one, I think I will get some other opinions.

Thanks so much for the dialog and I will just re-open this one if I need to report anything further.

**Comment by mclemente** [comment]
This should fix all those issues, update and check it out.

**Comment by danimrath** [comment]
Missing an import for f in sfrpg.js

**Comment by mclemente** [comment]
🤦‍♂️ should be fixed now.

**Comment by danimrath** [comment]
Lol, that did it. 
Hope you don't mind me continuing to offer suggestions here.
Little change I will be putting in my local copy. Updating the isCombatRunning function to check for combats that are started in the scene being viewed or unlinked started combats. 

	isCombatRunning() {
		return [...game.combats].some((combat) => combat.started && (combat._source.scene == canvas.scene._id || combat._source.scene == null));
	}

**Comment by mclemente** [comment]
I don't mind it, but I'll close this issue soon, so if you get more suggestions, consider opening an Issue, PR or a Discussion.

**Comment by danimrath** [comment]
Thanks a ton!
