### ISSUE TITLE
Death State on Condition doesn´t work on the Cyberpunk Red Module

### ISSUE THREAD

**Issue by UnaiAhedo** [mclemente/healthEstimate#172]
**Describe the bug**
When you mark "Death" on a token in Cyberpunk Red module, it's doesn't apply the Death State Name to the token.

**To Reproduce**
1. Activate Death State on Condition
2. Activate the "Death/Defeat" mark to the token.

**Expected behavior**
It should apply the Death State Name when you kill/defeat a token

**Screenshots**
[Link to the video.](https://drive.google.com/drive/folders/1GeLJeML2LVoW2q5RuU_40c9Ka_96q9xt)

**Game Specifics (please complete the following information):**
- Foundry version 10 Build 291
- Cyberpunk RED - Core v0.87.2

**Additional context**

**Comment by mclemente** [comment]
Since the latest version of Health Estimate (30.8.7), tokens are only shown as dead if they're marked as defeated in combat, so the non-combat video isn't a bug. Technically it wouldn't have worked even on earlier versions, as you should've right-clicked the status effect instead.
It was changed from checking for the overlay icon due to how some systems used different icons to represent a defeated token.

On the combat video, it was a bug and will be fixed on the next release.

**Comment by UnaiAhedo** [comment]
Didn't know about the first one, sorry for bothering with that.

Thanks for the fast answer!
