### ISSUE TITLE
Error: This is not a registered game setting

### ISSUE THREAD

**Issue by jocolamarco** [mclemente/healthEstimate#23]
**FVTT version:** 0.8.7
**Module Version:** 2.5.11 (latest)

After joining the world, the following error message is logged in the console:

![image](https://user-images.githubusercontent.com/45291719/123085282-f420e700-d419-11eb-8dde-885ad526f4fb.png)

**Comment by mclemente** [comment]
Does this happens every time or was it a one time thing? The only way for that error to happen is if Foundry somehow calls the ready hook before the setup hook so that it skips the register of the settings. I'm saying this because it happened to me before [discord report](https://discord.com/channels/170995199584108546/848968607526551592/849125310230167562) and that was the reason.

**Comment by jocolamarco** [comment]
@mclemente haven't seen it again...
