### ISSUE TITLE
Feature Request: Allow estimates to round down on fractions

### ISSUE THREAD

**Issue by King-Wedgie** [mclemente/healthEstimate#239]
**Is your feature request related to a problem? Please describe.**
I'm utilizing HE in a system that uses a health-threshold condition for certain effects (similar to "bloodied" from D&D4e); however, the system rounds all fractions *down*, whereas HE seems to always round *up*.

**Describe the solution you'd like**
A toggle to always round estimates down would fix the issue.

**Is this specific to system or is it system agnostic?**
I feel like this is a pretty system agnostic request, but I am running Fabula Ultima - specifically the [Project FU](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima) implementation if it matters.

**Comment by mclemente** [comment]
HE truncates percentages (only uses the integer part). If anything it is similar to rounding down. Something like. 42.85% (e.g. a 3/7 fraction) becomes 42%, not 43%.
So, if you mean to get something like "under 50%", you should be targetting at 49% instead of 50.

What fraction are you trying to set exactly?

**Comment by King-Wedgie** [comment]
>_"So, if you mean to get something like "under 50%", you should be targetting at 49% instead of 50."_

Oh whoops, that was all I needed. My bad on the request; I'll close it. Thought it was a rounding issue, turns out it was just user error.
