### ISSUE TITLE
Dead Icon not working on NPC's

### ISSUE THREAD

**Issue by Noshei** [mclemente/healthEstimate#5]
The Dead Icon doesn't appear to be getting applied to NPC's when they die.  I'm using 2.5.1.1, when I set an NPC to 0, it says dead for the estimate, but no Icon.

![image](https://user-images.githubusercontent.com/8866000/114223615-4713f380-992d-11eb-9dd2-e743030a03e1.png)

**Comment by Noshei** [comment]
Also, looks like the Mark Dead macro doesn't work either.

**Comment by mclemente** [comment]
The skull isn't auto-applied by this module, try using CUB's Triggler: https://imgur.com/a/8EixkB7
"Works independently from the macro" means `Death State on Condition` will check for the icon set on `Death Marker`. Normally, it would only check for 0 HP on NPCs (if `NPCs die immediately` was checked) or NPC's or if it was targetted by the Mark Dead macro.
`Death State Name` is the text that will show for dead tokens.
`Death Marker`'s function is to define if the token is dead if it has that icon over it (e.g. for system that use another icon instead of the skull).
I'll update the descriptions to avoid confusion.

**Comment by Noshei** [comment]
You may also want to edit the main image for the module, as it give the impression that this module applies the skull icon to dead NPC's.
