### ISSUE TITLE
Module does not appear to work with Wrath & Glory system

### ISSUE THREAD

**Issue by maddoodles** [mclemente/healthEstimate#84]
Hello. I don't know if this is likely to be because of the Game System or this module, however I am getting an error in the console, and estimated health does not display, when I attempt to use this module with Wrath & Glory.
```
Health Estimate | Error on getCharacters(). Token Name: 'Imperial Citizen'. Type: 'threat' Error: The Hit Points Attribute Data Path setting ("data.combat.wounds.value") is wrong.
    at fraction (generic.js:11)
    at getFraction (logic.js:87)
    at getCharacters (logic.js:12)
    at healthEstimate.js:158
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at Canvas.draw (foundry.js:20143)
    at async Scene.view (foundry.js:17859)
    at async Game.initializeCanvas (foundry.js:5677)
    at async Game.setupGame (foundry.js:5548)
    at async Game._initializeGameView (foundry.js:6514)
    at async Game.initialize (foundry.js:5431)
```
The data path (data.combat.wounds.value) is the correct path for current hit points is correct for current hit points, however.

Thank you for your time.

**Comment by mclemente** [comment]
Try `data.combat.wounds` instead. It needs to access both `value` and `max` to calculate the estimate.

**Comment by maddoodles** [comment]
Unfortunately, I get the same result.

**Comment by mclemente** [comment]
Oops, it's `actor.data.data.combat.wounds`. Also, do threats have some kind of HP to be tracked?

**Comment by maddoodles** [comment]
Hey, it works, awesome!
Threats track their HP in the same way Agents do, in fact I can confirm the module works for both. 

Amazing, thank you very much. If it's not too much trouble may I ask how you found the correct path? It might be future for troubleshooting future modules. :)

**Comment by mclemente** [comment]
>how you found the correct path?

It should always start with `actor.data.data` (or `actor.system` on Foundry V10) because the input is the token.

As for looking at the character data, select a token on the map, open the console (F12), type `_token.actor.data.data` and it'll return the actor's data.

As for your edit, I can't help right now because I'm on Foundry V10 and the overlay is bugged currently. I'll try this later tomorrow on my V9 installation.

**Comment by maddoodles** [comment]
Once again, thank you very much. :)

**Comment by mclemente** [comment]
Hm, is it supposed to look like this?
![image](https://user-images.githubusercontent.com/5288872/178124445-21f02473-ea2e-4596-9b66-8eaae372bed0.png)
Because that is what I'm seeing and it's a texture error. It should be `systems/wrath-and-glory/asset/icons/dead.svg` but it isn't loading for me for whatever reason.

**Comment by maddoodles** [comment]
That's odd, I do have the svg. Maybe reinstalling would fix that, if not I could always send the file over if that would help.
It should look like this:
![image](https://user-images.githubusercontent.com/82548443/178124593-fc0f14e3-900c-4b64-a1fc-bd0ba410042c.png)

**Comment by mclemente** [comment]
That's good to hear. I'm closing this issue, then.
